server:
  port: 8585

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/contacts
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: contacts_schema



