version: '3.9'
services:
  postgres_db:
    container_name: book_db
    image: postgres:15.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=book_db
    volumes:
      - database-data:/var/lib/postgresql/data/

  redis:
    container_name: book_redis
    image: redis:7.0.12
    ports:
      - "6379:6379"

volumes:
  database-data:

